services:
  db:
    image: postgres:latest
    container_name: integration-tests-prisma
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_PASSWORD=prisma
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  database:
    driver: local